import { chromium } from 'playwright';
const b = await chromium.launch({ headless: true });
const p = await (await b.newContext({ viewport: { width: 1600, height: 1000 } })).newPage();
await p.goto('http://localhost:4321/?composite=0', { waitUntil: 'load' });
await new Promise(r => setTimeout(r, 1500));
await p.keyboard.press('Enter');
await new Promise(r => setTimeout(r, 8000));
await p.screenshot({ path: 'shots/review0613/idle-graded.png' });
console.log('captured');
await b.close();
