import { chromium } from 'playwright';
const OUT = process.argv[2] || 'shots/goal0612/p2-idle.png';
const b = await chromium.launch({ headless: true });
const p = await (await b.newContext({ viewport: { width: 1400, height: 900 } })).newPage();
await p.goto('http://localhost:4321/', { waitUntil: 'load' });
await new Promise(r => setTimeout(r, 1500));
await p.keyboard.press('Enter');
await new Promise(r => setTimeout(r, 7000));
await p.screenshot({ path: OUT });
console.log('captured', OUT);
await b.close();
