// Verify the built adaptive desktop without replacing its live iframe.
// node scripts/verify-reading.mjs [base URL] [screenshot directory]
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const base=(process.argv[2] || 'http://localhost:4325').replace(/\/$/,'');
const shots=process.argv[3] || 'shots/reading-sandbox/adaptive';
await mkdir(shots,{recursive:true});
const browser=await chromium.launch({headless:true});
const ctx=await browser.newContext({viewport:{width:411,height:650},deviceScaleFactor:1});
const page=await ctx.newPage();
page.setDefaultTimeout(60000);
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const shot=name=>page.screenshot({path:`${shots}/${name}.png`});
const screen=page.locator('iframe[title="prashantgarg.os"]');
const desktop=page.frameLocator('iframe[title="prashantgarg.os"]');
try {
  await page.goto(`${base}/?app=home`,{waitUntil:'load'});
  await page.locator('.office-monitor[data-ready="true"]').waitFor();
  await desktop.locator('.win95-desktop:not([inert])').waitFor();
  await desktop.locator('body').evaluate(()=>document.fonts.ready);
  await page.locator('#office[data-view="desktop"]').waitFor();
  const box=await screen.boundingBox();
  assert(box && Math.abs(box.width-411)<2 && Math.abs(box.height-650)<2,JSON.stringify(box));
  await screen.evaluate(el=>el.dataset.continuity='screen');
  await shot('narrow-home');
  await desktop.getByRole('button',{name:'Research',exact:true}).click();
  const article=desktop.frameLocator('iframe.win95-iframe');
  await article.locator('h1').waitFor();
  await desktop.locator('.win95-window:not(.opening)').waitFor();
  await desktop.locator('.win95-content > [aria-hidden="true"]').waitFor({state:'detached'});
  await desktop.locator('iframe.win95-iframe').evaluate(el=>el.dataset.continuity='paper');
  assert(await article.locator('html').evaluate(el=>el.scrollWidth<=innerWidth));
  const close=await desktop.getByRole('button',{name:'Close',exact:true}).boundingBox();
  assert(close && close.x>=0 && close.x+close.width<=412);
  await shot('narrow-research');
  await article.locator('.paper-abstract summary').first().click();
  await article.locator('html').evaluate(()=>window.scrollTo(0,320));
  const originalScroll=await article.locator('html').evaluate(()=>window.scrollY);
  await page.setViewportSize({width:1400,height:900});
  await page.locator('#office[data-view="room"]').waitFor();
  await page.waitForTimeout(1000);
  await shot('monitor');
  await desktop.getByRole('button',{name:'Desktop view',exact:true}).click();
  await page.locator('#office[data-view="desktop"]').waitFor();
  await page.waitForTimeout(500);
  const expanded=await screen.boundingBox();
  assert(expanded && Math.abs(expanded.width-1400)<2 && Math.abs(expanded.height-900)<2);
  assert.equal(await screen.getAttribute('data-continuity'),'screen');
  assert.equal(await desktop.locator('iframe.win95-iframe').getAttribute('data-continuity'),'paper');
  assert.equal(await article.locator('.paper-abstract[open]').count(),1);
  assert(Math.abs(await article.locator('html').evaluate(()=>window.scrollY)-originalScroll)<3);
  await shot('expanded-paper');
  await desktop.getByRole('button',{name:'Back to the office',exact:true}).click();
  await page.locator('#office[data-phase="idle"]').waitFor();
  await page.waitForTimeout(1000);
  await shot('room');
  await page.keyboard.press('Enter');
  await page.locator('#office[data-phase="desktop"][data-view="desktop"]').waitFor();
  await desktop.locator('.win95-desktop:not([inert])').waitFor();
  assert.equal(await desktop.locator('iframe.win95-iframe').getAttribute('data-continuity'),'paper');
  await desktop.getByRole('button',{name:'Desktop view',exact:true}).click();
  await page.locator('#office[data-view="room"]').waitFor();
  await page.setViewportSize({width:411,height:650});
  await page.locator('#office[data-view="desktop"]').waitFor();
  assert.equal(await screen.getAttribute('data-continuity'),'screen');
  await shot('narrow-return');
  assert.deepEqual(errors,[]);
  console.log('PASS: adaptive sizing, readable narrow pages, same iframe, abstract/scroll continuity, Room/Desktop controls.');
} catch(e) {
  await shot('failure');
  console.log('errors',errors);
  throw e;
} finally {await browser.close();}
