// Check the built office: node scripts/verify-office.mjs [base URL] [shot directory]
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const baseUrl = (process.argv[2] || 'http://localhost:4321').replace(/\/$/, '');
const outputDir = process.argv[3] || 'shots/office-check';
await mkdir(outputDir, {recursive:true});
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1400, height: 900 }, deviceScaleFactor: 1 });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', msg => { if (msg.type() === 'error') console.log('console:', msg.text()); });
const shot = name => page.screenshot({path: `${outputDir}/${name}.png`});
try {
  await page.goto(`${baseUrl}/`, {waitUntil: 'load'});
  await page.locator('.office-monitor[data-ready="true"]').waitFor({timeout: 60000});
  await page.getByRole('button', {name: 'ENTER', exact: true}).waitFor();
  await shot('start');
  assert.equal(await page.evaluate(() => sessionStorage.getItem('pg_phase')), null);
  await page.getByRole('button', {name: 'ENTER', exact: true}).click();
  await page.locator('#office[data-phase="idle"]').waitFor({timeout: 60000});
  await page.waitForTimeout(2500);
  await shot('room');
  const frame = page.frameLocator('iframe[title="prashantgarg.os"]');
  assert.equal(await frame.locator('.win95-home-name').innerText(), 'Prashant Garg');
  await page.locator('iframe[title="prashantgarg.os"]').evaluate(el => el.dataset.continuity = 'same-frame');
  await page.keyboard.press('Enter');
  await page.waitForTimeout(650);
  await shot('approach');
  await page.locator('#office[data-phase="desktop"]').waitFor({timeout: 60000});
  await frame.locator('.win95-desktop:not([inert])').waitFor();
  await page.waitForTimeout(800);
  await shot('desktop');
  assert.equal(await page.locator('iframe[title="prashantgarg.os"]').getAttribute('data-continuity'), 'same-frame');
  await frame.getByRole('button', {name:'Research', exact:true}).dblclick();
  await frame.locator('.win95-window').waitFor();
  await frame.frameLocator('iframe.win95-iframe').locator('h1').waitFor();
  await shot('research');
  await page.getByRole('button', {name: 'Room Esc'}).click();
  await page.waitForTimeout(650);
  await shot('return');
  await page.locator('#office[data-phase="idle"]').waitFor({timeout:60000});
  await shot('room-returned');
  assert.equal(await page.evaluate(() => sessionStorage.getItem('pg_phase')), null);
  assert.equal(await page.locator('iframe[title="prashantgarg.os"]').getAttribute('data-continuity'), 'same-frame');
  await page.keyboard.press('Enter');
  await page.locator('#office[data-phase="desktop"]').waitFor({timeout:60000});
  assert.equal(await frame.locator('.win95-window').count(), 1);
  await frame.locator('.win95-desktop:not([inert])').waitFor();
  await page.waitForTimeout(800);
  await frame.locator('.win95-titlebar').click();
  assert.equal(await page.evaluate(()=>document.activeElement?.tagName), 'IFRAME');
  await page.keyboard.press('Escape');
  await frame.locator('.win95-window').waitFor({state:'detached'});
  await page.keyboard.press('Escape');
  await page.locator('#office[data-phase="idle"]').waitFor({timeout:60000});
  const monitorBox = await page.locator('.office-monitor-enter').boundingBox();
  assert(monitorBox);
  await page.mouse.click(monitorBox.x+monitorBox.width/2, monitorBox.y+monitorBox.height/2);
  await page.locator('#office[data-phase="desktop"]').waitFor({timeout:60000});
  await page.reload({waitUntil:'load'});
  await page.locator('#office[data-phase="desktop"]').waitFor();
  await page.locator('.office-monitor[data-ready="true"]').waitFor({timeout:60000});
  assert.deepEqual(errors, []);
  console.log('PASS: live monitor, window persistence, mouse/keyboard entry, Escape, return and reload.');
} catch(e) {
  await shot('failure');
  console.log('phase', await page.locator('#office').getAttribute('data-phase'), 'frames', page.frames().map(f => f.url()), 'errors', errors);
  throw e;
} finally { await browser.close(); }
